---
kind: pipeline
type: kubernetes
name: build-webtop-steam

metadata:
  namespace: drone

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    registry: registry.home.sud0.com
    repo: webtop-steam
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
